
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TimeTracks.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Account
{

    public Account()
    {

        this.Companies = new HashSet<Company>();

        this.Users = new HashSet<User>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public Days WeekStart { get; set; }



    public virtual ICollection<Company> Companies { get; set; }

    public virtual ICollection<User> Users { get; set; }

}

}
