
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TimeTracks.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Adderess
{

    public int Id { get; set; }

    public string StreetAdderess { get; set; }

    public string Suite { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public int ZipCode { get; set; }

    public Nullable<bool> Primary { get; set; }

    public string Country { get; set; }



    public virtual Location Location { get; set; }

    public virtual Company Company { get; set; }

}

}
