
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TimeTracks.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Company
{

    public Company()
    {

        this.Locations = new HashSet<Location>();

        this.PhoneNumbers = new HashSet<PhoneNumber>();

        this.Punches = new HashSet<Punch>();

    }


    public int Id { get; set; }

    public string Name { get; set; }



    public virtual Account Account { get; set; }

    public virtual ICollection<Location> Locations { get; set; }

    public virtual Adderess Adderess { get; set; }

    public virtual ICollection<PhoneNumber> PhoneNumbers { get; set; }

    public virtual ICollection<Punch> Punches { get; set; }

}

}
