
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TimeTracks.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Job
{

    public Job()
    {

        this.Notes = new HashSet<Note>();

    }


    public int Id { get; set; }

    public System.DateTime StartDateTime { get; set; }

    public System.DateTime EndDateTime { get; set; }

    public bool Complete { get; set; }



    public virtual ICollection<Note> Notes { get; set; }

    public virtual Location Location { get; set; }

    public virtual Punch Punch { get; set; }

}

}
