
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TimeTracks.Data
{

using System;
    using System.Collections.Generic;
    
public partial class LocationLog
{

    public LocationLog()
    {

        this.Id = 1000;

    }


    public int Id { get; set; }

    public double Latitude { get; set; }

    public double Longitude { get; set; }

    public System.DateTime TimeStamp { get; set; }



    public virtual Device Device { get; set; }

}

}
