
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TimeTracks.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Location
{

    public Location()
    {

        this.PhoneNumbers = new HashSet<PhoneNumber>();

        this.Jobs = new HashSet<Job>();

    }


    public int Id { get; set; }

    public string Name { get; set; }



    public virtual Adderess Adderess { get; set; }

    public virtual ICollection<PhoneNumber> PhoneNumbers { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<Job> Jobs { get; set; }

}

}
