
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TimeTracks.Data
{

using System;
    

public enum NumberTypes : int
{

    Cell = 0,

    Home = 1,

    Office = 2,

    Work = 3,

    Fax = 4,

}

}
