
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TimeTracks.Data
{

using System;
    using System.Collections.Generic;
    
public partial class PayOut
{

    public int Id { get; set; }

    public decimal Amount { get; set; }

    public System.DateTime Date { get; set; }

    public int EnteredBy { get; set; }

    public bool Approved { get; set; }

    public int ApprovedBy { get; set; }



    public virtual User User { get; set; }

}

}
