
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TimeTracks.Data
{

using System;
    using System.Collections.Generic;
    
public partial class PhoneNumber
{

    public int Id { get; set; }

    public int AreaCode { get; set; }

    public int Number { get; set; }

    public NumberTypes Type { get; set; }

    public string Extension { get; set; }

    public Nullable<bool> Primary { get; set; }



    public virtual Location Location { get; set; }

    public virtual Company Company { get; set; }

    public virtual User User { get; set; }

}

}
