

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TimeTracks.Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TimeTracksContainer : DbContext
{
    public TimeTracksContainer()
        : base("name=TimeTracksContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<User> Users { get; set; }

    public DbSet<Company> Companies { get; set; }

    public DbSet<Adderess> Adderesses { get; set; }

    public DbSet<PhoneNumber> PhoneNumbers { get; set; }

    public DbSet<Location> Locations { get; set; }

    public DbSet<Job> Jobs { get; set; }

    public DbSet<Device> Devices { get; set; }

    public DbSet<Note> Notes { get; set; }

    public DbSet<Account> Accounts { get; set; }

    public DbSet<Punch> Punches { get; set; }

    public DbSet<PayOut> PayOuts { get; set; }

    public DbSet<LocationLog> LocationLogs { get; set; }

}

}

