
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TimeTracks.Data
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public User()
    {

        this.PhoneNumbers = new HashSet<PhoneNumber>();

        this.Devices = new HashSet<Device>();

        this.PayOuts = new HashSet<PayOut>();

    }


    public int Id { get; set; }

    public string UserName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public RoleTypes Role { get; set; }

    public Nullable<decimal> PayRate { get; set; }

    public Nullable<PayIntervals> PayInterval { get; set; }

    public string Email { get; set; }

    public bool Active { get; set; }

    public string ASPid { get; set; }



    public virtual Account Account { get; set; }

    public virtual ICollection<PhoneNumber> PhoneNumbers { get; set; }

    public virtual ICollection<Device> Devices { get; set; }

    public virtual ICollection<PayOut> PayOuts { get; set; }

}

}
